## Custom notifications
notify:
  webhooks:
    # A list of hashes representing hooks. Only the url field is supported.
    - url: https://outlook.office.com/webhook/d8aaf6c6-0083-4df3-a0e0-779fa0b5c8b8@72f988bf-86f1-41af-91ab-2d7cd011db47/TravisCI/7536652baff3469e96673de8dc5f057d/929c16ef-8d0d-46ca-a0c3-559937d6bd2c
    - url: http://requestb.in/14948qw1
